### PR TITLE
Add is_betting_active flag to IChallenge

### PR DESCRIPTION
**Pull request by flogan**

### CODE REVIEW

**Comment by judegiordano** [comment]
wait whats this bool for exactly?

**Comment by flogan** [comment]
a feature to close betting before the actual challenge / conceding

**Comment by cdleveille** [comment]
It's so people can't cheat and place a bet after the challenge takes place but before the concede command gets run.

**Review by cdleveille — APPROVED** [review]

**Comment by judegiordano** [comment]
lgtm, feel free to merge whenever

**Review by judegiordano — APPROVED** [review]

**Pull request merged**
